[package]
name = "day_1"
version = "0.1.0"
authors = ["a.kulinskiy <a.kulinskiy@tinkoff.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-array = "0.4.4"
typenum = "1.12.0"
